const CHAVE_NEWSAPI = "SUA CHAVE NEWS API AQUI";
const CHAVE_EXCHANGERATE = "SUA CHAVE EXCHANGERATE API AQUI";
const CHAVE_TMDB = "SUA CHAVE TMDB AQUI";

module.exports = CHAVE_NEWSAPI, CHAVE_EXCHANGERATE, CHAVE_TMDB